segunda  Workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,22 +1,22 @@
 name: Building Blocks
 
 on:
- push:
- workflow_dispatch:
+  push:
+  workflow_dispatch:
 
- jobs: 
-   echo-hello:
-     runs-on: ubuntu-latest
-     steps:
-      -name: Say hello
-      run : echo "Hello,World!"
-
-   echo-goodbye:
+jobs:
+  echo-hello:
     runs-on: ubuntu-latest
     steps:
-      -name: Faleid step
-      run: |
-        echo "I will fail"
-        exit 1
-      -name: Say goodbye
-      run: echo "Goodbye!"  
+      - name: Say hello
+        run: echo "Hello, World!"
+
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say goodbye
+        run: echo "Goodbye!"
